### ISSUE TITLE
Sync or async?

### ISSUE THREAD

**Issue by mhulse** [btwael/locallydb#14]
Stupid question, but … Are the operations/methods sync or async?

**Comment by btwael** [comment]
@mhulse sorry, but I don't understand exactly what do you mean? can you clarify your question?
if you mean that are functions/methods in mammouth are async or sync, mammouth compiles to PHP, all operations in PHP are sync.

**Comment by btwael** [comment]
All functions are sync.

**Comment by mhulse** [comment]
> All functions are sync.

Awesome, thank you! I really appreciate it! 👍
