### ISSUE TITLE
`Collection.remove` does not save to disk after remove but in loop before remove 

### ISSUE THREAD

**Issue by fbender** [btwael/locallydb#8]
Going through the source Code of `collection.coffee`, I noticed [something odd in the `remove` method](https://github.com/btwael/locallydb/blob/master/src/collection.coffee#L105-L106) when `autosave = true`. Since I don't know CS, I checked the compiled source and confirmed my suspicion: 

1. `save` is called in every loop iteration 
2. … until the element to be removed is found, which is then deleted but the changes are not written to disk. 

So [this](https://github.com/btwael/locallydb/blob/master/src/collection.coffee#L101-L107) should probably read like:
```cs
remove: (cid) ->
    for element, i in @items
        if element.cid is cid
            @items.remove i
            @save() if @autosave
            return true
    return false
```

**Comment by btwael** [comment]
Yes! the code should be like you mentioned! I don't have a computer at this moment to modify the code!
Thank you :)

**Comment by fbender** [comment]
Thank you! I'm currently working around this with disabling `autosave` before remove, doing a manual `save` and reenabling `autosave` afterwards. Let me know when you come around to fix this and publish the update on NPM!

**Comment by btwael** [comment]
You can now check the corrected version at npm!
